---
name: 🔆 Umbraco Heartcore Forms Library Issue
description: "Create issues/feature requests for our Umbraco Heartcore Forms libraries"
body:
- type: textarea
  id: "description"
  attributes:
    label: "Issue description"
    description: "Write a summary of the issue you want to report."
  validations:
    required: true
